// SEARCH:
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
// AUTH:
export const SET_AUTH = "SET_AUTH";
export const UNSET_AUTH = "UNSET_AUTH";
// LISTS:
export const SET_HOME_LAST = "SET_HOME_LAST";
// QUEUE:
export const SET_PLAYING = "SET_PLAYING";
export const SET_QUEUE_VISIBLE = "SET_QUEUE_VISIBLE";
export const ADD_QUEUE_SONGS = "ADD_QUEUE_SONGS";
export const REPLACE_QUEUE_SONGS = "REPLACE_QUEUE_SONGS";
export const REMOVE_QUEUE_INDEX = "REPLACE_QUEUE_INDEX";
export const SET_CURRENT_SONG_INDEX = "SET_CURRENT_SONG_INDEX";
export const MOVE_QUEUE_NEXT_SONG = "MOVE_QUEUE_NEXT_SONG";
export const MOVE_QUEUE_PREV_SONG = "MOVE_QUEUE_PREV_SONG";
